title: Nathan Wang-Ly
email_user: nathanwangly
email_domain: gmail.com
description: Personal website
baseurl: "" 
url: "https://nathanwangly.github.io"

permalink: /posts/:year/:month/:day/:title/

# Build settings
plugins:
  - jekyll-feed

collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title/
  projects:
    output: true
    permalink: /projects/:title/